# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bonsai < Formula
  desc "CLI tool for scaffolding Claude Code agent workspaces"
  homepage "https://github.com/LastStep/Bonsai"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.3.0/bonsai_0.3.0_darwin_amd64.tar.gz"
      sha256 "4b0f70b6e3332b0dc68baa0c21d449cd5b197c6bbbdf747799889d25cc0ebf51"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.3.0/bonsai_0.3.0_darwin_arm64.tar.gz"
      sha256 "d343df904df9eebb566c27a220e3b7e2b9de554e24871ce7ebda5f4e4ecb77bc"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.3.0/bonsai_0.3.0_linux_amd64.tar.gz"
      sha256 "687a55b4b1d4c71dcf320d6c57cc72073abdc352594c959be62b489d88c8f0f1"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.3.0/bonsai_0.3.0_linux_arm64.tar.gz"
      sha256 "9884f671b748da6d0cc76a43c9c8098d51da40c72b2da2ecd54abc46a17cfa7a"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  test do
    system "#{bin}/bonsai", "--version"
  end
end
