# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bonsai < Formula
  desc "CLI tool for scaffolding Claude Code agent workspaces"
  homepage "https://github.com/LastStep/Bonsai"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.4.2/bonsai_0.4.2_darwin_amd64.tar.gz"
      sha256 "d8df35251469ccecdabf2deefb93e3b57e0f4edd331d68f4d33024f16df1d9b8"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.4.2/bonsai_0.4.2_darwin_arm64.tar.gz"
      sha256 "d028972b371108b22ad6885106a941924b56cfee9ac15147ec228196972fc79d"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.4.2/bonsai_0.4.2_linux_amd64.tar.gz"
      sha256 "f20339a94701aa51a2a6edd42496ffd25bf8986908e4e8afad148d70a558cbdb"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LastStep/Bonsai/releases/download/v0.4.2/bonsai_0.4.2_linux_arm64.tar.gz"
      sha256 "cd9e10fd4781d58877fa2e8365cba7e8f89d431a568e1d0adbea00b333ba15f7"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  test do
    system "#{bin}/bonsai", "--version"
  end
end
